#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0

"""Generate SLOTS.md — the definitive slot reference, derived from the blocks
themselves so it can't go stale. Run after adding/renaming slots:
    python3 scripts/gen_slots_doc.py
"""
import collections
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Where each slot family renders (from the generator,
# engine/src/generator.ts).
DEST = [
    ('main_', 'main/app_main.cpp'),
    ('config_', 'components/app_config (generated header)'),
    ('logic_', 'components/app_logic'),
    ('matter_', 'components/app_matter (rendered only when frameworks includes matter)'),
    ('rainmaker_', 'components/app_rainmaker (only with rainmaker)'),
    ('zigbee_', 'components/app_zigbee (only with zigbee)'),
    ('ble_mesh_', 'components/app_ble_mesh (only with ble_mesh)'),
    ('audio_', 'components/app_audio (only with audio)'),
    ('mqtt_', 'components/app_mqtt (only with mqtt)'),
    ('display_', 'components/app_display (only with display)'),
    ('vision_', 'components/app_vision (only with vision)'),
    ('ble_hid_', 'components/app_ble_hid (only with ble_hid)'),
    ('espnow_', 'components/app_espnow (only with espnow)'),
    ('webui_', 'components/app_webui (only with webui)'),
    ('agents_', 'components/app_agents (only with agents)'),
    ('sound_', 'components/app_sound (only with sound)'),
    ('driver_', 'components/app_driver'),
]


# Slots the ENGINE defines with a built-in default body. Zero blocks may use
# one of these, so scanning code_blocks/*/slots cannot discover them — they
# must be declared here or a block author reading SLOTS.md never learns the
# slot exists. Keep in sync with the `collectSlot(...) ||` sites in
# engine/src/generator.ts (grep for "Defaulted slot").
DEFAULTED = {
    'matter_last_fabric_cases':
        'a contribution REPLACES the built-in handler (factory reset when the '
        'last fabric is removed — without some handler the device can never be '
        'commissioned again)',
}


def dest_for(slot: str) -> str:
    for prefix, dest in DEST:
        if slot.startswith(prefix):
            return dest
    return 'see the generator (firmware/services/src/templates/generator.ts)'


def main() -> None:
    usage: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    for slots_dir in sorted(ROOT.glob('code_blocks/*/*/slots')):
        kind_folder = slots_dir.parent.parent.name
        for f in slots_dir.iterdir():
            if f.suffix in ('.c', '.h'):
                usage[f.stem][kind_folder] += 1

    lines = [
        '# Slot reference',
        '',
        'Every slot that exists across the blocks — generated by',
        '`scripts/gen_slots_doc.py`, so this list cannot go stale. A slot is a',
        'named C fragment (`slots/<name>.c|.h`) that the ZeroCode generator',
        'stitches into the firmware tree at the destination below.',
        '`{{prefix}}` / `{{prefix_lc}}` / `{{cfg.<param>}}` placeholders are',
        'substituted per block instance.',
        '',
        '**A slot can be taken away.** When a product runs on a board, a',
        'block whose `bmgr:` mapping lists a slot in `replaces_slots:` does NOT',
        'render it — esp-board-manager configures that hardware instead, so the',
        'line has one owner rather than two. Everything else the block',
        'contributes still renders. Write slots so that dropping the init one',
        'means "somebody else brings this hardware up", not "the block is gone":',
        'keep behaviour (`driver_apply_cases`, `logic_*`) out of the slot the',
        'board manager replaces. See CLAUDE.md → Boards (`board.yaml` + `bmgr:`).',
        '',
        '| slot | renders into | used by |',
        '|---|---|---|',
    ]
    for slot in sorted(usage.keys() | DEFAULTED.keys()):
        if slot in usage:
            used = ' · '.join(f'{n}× {k}' for k, n in usage[slot].most_common())
        else:
            used = 'no blocks yet — engine default applies'
        note = f' — **defaulted**: {DEFAULTED[slot]}' if slot in DEFAULTED else ''
        lines.append(f'| `{slot}` | {dest_for(slot)}{note} | {used} |')
    (ROOT / 'SLOTS.md').write_text('\n'.join(lines) + '\n')
    print(f'SLOTS.md: {len(usage.keys() | DEFAULTED.keys())} slots documented')


if __name__ == '__main__':
    main()
